// <auto-generated />
using System;
using Exemplo.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM.Persistence.Migrations
{
    [DbContext(typeof(ExemploDbContext))]
    [Migration("20260113175637_GrupoUser")]
    partial class GrupoUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Exemplo.Domain.Model.AgendamentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VendaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VendaId");

                    b.ToTable("agendamento", (string)null);
                });

            modelBuilder.Entity("Exemplo.Domain.Model.CondicaoVendaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("condicaoVenda", (string)null);
                });

            modelBuilder.Entity("Exemplo.Domain.Model.ExemploModel", b =>
                {
                    b.Property<int>("Campo1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Campo1"));

                    b.Property<string>("Campo2")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Campo3")
                        .HasColumnType("integer");

                    b.HasKey("Campo1");

                    b.HasIndex("Campo1");

                    b.ToTable("exemplo", (string)null);
                });

            modelBuilder.Entity("Exemplo.Domain.Model.GrupoVendaWhatsappModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdGrupo")
                        .HasColumnType("integer");

                    b.Property<int>("IdVendaWhats")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdVendaWhats");

                    b.ToTable("grupovendawhatsapp", (string)null);
                });

            modelBuilder.Entity("Exemplo.Domain.Model.GrupoWhatsappModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("grupowhatsapp", (string)null);
                });

            modelBuilder.Entity("Exemplo.Domain.Model.SedeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("DataInclusao")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("sede", (string)null);
                });

            modelBuilder.Entity("Exemplo.Domain.Model.ServicoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("servico", (string)null);
                });

            modelBuilder.Entity("Exemplo.Domain.Model.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Exemplo.Domain.Model.VendaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComoConheceu")
                        .HasColumnType("text");

                    b.Property<int?>("CondicaoVendaId")
                        .HasColumnType("integer");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contrato")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicial")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Fone")
                        .HasColumnType("text");

                    b.Property<int?>("Genero")
                        .HasColumnType("integer");

                    b.Property<string>("Indicacao")
                        .HasColumnType("text");

                    b.Property<string>("MotivoEscolha")
                        .HasColumnType("text");

                    b.Property<string>("Obs")
                        .HasColumnType("text");

                    b.Property<int?>("Origem")
                        .HasColumnType("integer");

                    b.Property<int?>("SedeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServicoId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ValorVenda")
                        .HasColumnType("numeric");

                    b.Property<int?>("VendedorAtualId")
                        .HasColumnType("integer");

                    b.Property<int>("VendedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CondicaoVendaId");

                    b.HasIndex("SedeId");

                    b.HasIndex("ServicoId");

                    b.HasIndex("VendedorAtualId");

                    b.HasIndex("VendedorId");

                    b.ToTable("venda", (string)null);
                });

            modelBuilder.Entity("Exemplo.Domain.Model.VendaWhatsappModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("VendaId")
                        .HasColumnType("integer");

                    b.Property<string>("WhatsappChatId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatsappUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VendaId")
                        .IsUnique();

                    b.ToTable("vendawhatsapp", (string)null);
                });

            modelBuilder.Entity("Exemplo.Domain.Model.AgendamentoModel", b =>
                {
                    b.HasOne("Exemplo.Domain.Model.VendaModel", "Venda")
                        .WithMany("Agendamentos")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Exemplo.Domain.Model.GrupoVendaWhatsappModel", b =>
                {
                    b.HasOne("Exemplo.Domain.Model.GrupoWhatsappModel", "GrupoWhatsapp")
                        .WithMany("GruposVendaWhatsapp")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Exemplo.Domain.Model.VendaWhatsappModel", "VendaWhatsapp")
                        .WithMany("GruposVendaWhatsapp")
                        .HasForeignKey("IdVendaWhats")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GrupoWhatsapp");

                    b.Navigation("VendaWhatsapp");
                });

            modelBuilder.Entity("Exemplo.Domain.Model.GrupoWhatsappModel", b =>
                {
                    b.HasOne("Exemplo.Domain.Model.UsuarioModel", "Usuario")
                        .WithMany("GruposWhatsapp")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Exemplo.Domain.Model.VendaModel", b =>
                {
                    b.HasOne("Exemplo.Domain.Model.CondicaoVendaModel", "CondicaoVenda")
                        .WithMany("Vendas")
                        .HasForeignKey("CondicaoVendaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Exemplo.Domain.Model.SedeModel", "Sede")
                        .WithMany("Vendas")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Exemplo.Domain.Model.ServicoModel", "Servico")
                        .WithMany("Vendas")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Exemplo.Domain.Model.UsuarioModel", "VendedorAtual")
                        .WithMany("VendasAtuais")
                        .HasForeignKey("VendedorAtualId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Exemplo.Domain.Model.UsuarioModel", "Vendedor")
                        .WithMany("Vendas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CondicaoVenda");

                    b.Navigation("Sede");

                    b.Navigation("Servico");

                    b.Navigation("Vendedor");

                    b.Navigation("VendedorAtual");
                });

            modelBuilder.Entity("Exemplo.Domain.Model.VendaWhatsappModel", b =>
                {
                    b.HasOne("Exemplo.Domain.Model.VendaModel", "Venda")
                        .WithOne("VendaWhatsapp")
                        .HasForeignKey("Exemplo.Domain.Model.VendaWhatsappModel", "VendaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Exemplo.Domain.Model.CondicaoVendaModel", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("Exemplo.Domain.Model.GrupoWhatsappModel", b =>
                {
                    b.Navigation("GruposVendaWhatsapp");
                });

            modelBuilder.Entity("Exemplo.Domain.Model.SedeModel", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("Exemplo.Domain.Model.ServicoModel", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("Exemplo.Domain.Model.UsuarioModel", b =>
                {
                    b.Navigation("GruposWhatsapp");

                    b.Navigation("Vendas");

                    b.Navigation("VendasAtuais");
                });

            modelBuilder.Entity("Exemplo.Domain.Model.VendaModel", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("VendaWhatsapp");
                });

            modelBuilder.Entity("Exemplo.Domain.Model.VendaWhatsappModel", b =>
                {
                    b.Navigation("GruposVendaWhatsapp");
                });
#pragma warning restore 612, 618
        }
    }
}
